name: Static analysis

on: [ push, pull_request ]

jobs:
    testsuite:
        name: all tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ '8.1' ]
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Composer install
                run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s composerInstall

            -   name: Lint PHP
                run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

            -   name: Unit Tests
                run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit
    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    -   php-version: 7.4
                    -   php-version: 8.0
                    -   php-version: 8.1
        steps:
            -   uses: actions/checkout@v2

            -   id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ matrix.php-version }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: none

            -   run: composer install --no-progress

            -   run: vendor/bin/phpstan analyse Classes -c phpstan.neon