name: Static analysis

on: [ push, pull_request ]

jobs:
    psalm:
        name: Running Psalm
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Psalm
                uses: docker://vimeo/psalm-github-actions