name: Static analysis

on: [ push, pull_request ]

jobs:
    psalm:
        name: Running Psalm
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Psalm
                uses: docker://vimeo/psalm-github-actions
    php-stan:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Build composer
                uses: php-actions/composer@v6 # or alternative dependency management
                with:
                    php_version: 7.3
            -   uses: php-actions/phpstan@v3